export const LDAP_ERROR_CODES = {
	PROVIDER_CONFIG_NOT_FOUND: 'LDAP_PROVIDER_CONFIG_NOT_FOUND',
	AUTHENTICATION_FAILED: 'LDAP_AUTHENTICATION_FAILED',
	CREDENTIAL_INVALID: 'LDAP_CREDENTIAL_INVALID',
	IDENTITY_NOT_FOUND: 'LDAP_IDENTITY_NOT_FOUND',
	IDENTITY_AMBIGUOUS: 'LDAP_IDENTITY_AMBIGUOUS',
	USER_INFO_MISSING: 'LDAP_USER_INFO_MISSING',
	USER_EMAIL_MISSING: 'LDAP_USER_EMAIL_MISSING',
	USER_ID_MISSING: 'LDAP_USER_ID_MISSING',
	USER_NAME_MISSING: 'LDAP_USER_NAME_MISSING',
	LINK_ERROR: 'LDAP_LINK_ERROR',
} as const
